---
# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  application:
    name: "example"
  profiles:
    active: [ ]
    include:
      - "hello"
  autoconfigure:
    exclude:
      - "org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration"
  aop:
    auto: true
  main:
    web-application-type: servlet
    banner-mode: off
    allow-bean-definition-overriding: true
    lazy-initialization: false
    log-startup-info: true
    cloud-platform: none
    register-shutdown-hook: true
    sources: [ ]
  jackson:
    locale: "zh_CN"
    time-zone: "Asia/Shanghai"
    date-format: "yyyy-MM-dd HH:mm:ss.SSS"
    default-property-inclusion: always
    serialization:
      indent-output: true
      fail-on-self-references: true
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
      write-null-map-values: true
      write-empty-json-arrays: true
      write-single-elem-arrays-unwrapped: false
      write-enums-using-to-string: true
    deserialization:
      fail-on-unknown-properties: false
  lifecycle:
    timeout-per-shutdown-phase: "30s"
  jmx:
    enabled: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      enabled: true
      max-file-size: "1GB"
      max-request-size: "2GB"

server:
  port: 8080
  ssl:
    enabled: false
  servlet:
    context-path: "/"
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    min-response-size: "1KB"
  shutdown: graceful
